import type light from './light';

export type ColorScheme = typeof light;
// {
//   primary: string;
//   primary1: string;
//   accent: string;
//   secondary: string;
//   background: string;
//   error: string;
//   text: string;
//   disabled: string;
//   placeholder: string;
//   backdrop: string;
//   notification: string;
//   transparent: string;
//   buttonDisabledText: string;
//   buttonText: string;
//   white: string;
//   black: string;
//   danger: string;
//   success: string;
//   warning: string;
//   divider: string;
//   border: string;
//   icon: string;
//   inputTextColor: string;
//   inputBackground: string;
//   inputBorder: string;
//   inputDisabled: string;
//   required: string;
//   skeleton: string;
//   skeletonHighlight: string;
// };
